/*
============================================================================
DDL Script: Create Bronze Tables
============================================================================
Script Purpose:
  This script create tables in the "Bronze" schema, dropping existing tables
if they already exist.
Run this script to redefine the DDL structure of 'Bronze' Tables
============================================================================
*/

USE YankeesPitchDataWH

IF OBJECT_ID('bronze.pitch_data_filtered_batters', 'U') IS NOT NULL
	DROP TABLE bronze.pitch_data_filtered_batters;

CREATE TABLE bronze.pitch_data_filtered_batters (
	pitch_type									NVARCHAR(50),
	game_date									DATE,
	release_speed								FLOAT,
	release_pos_x								FLOAT,
	release_pos_z								FLOAT,
	player_name									NVARCHAR(50),
	batter										INT,
	pitcher										INT,
	events_										NVARCHAR(250),
	description_								NVARCHAR(250),
	spin_dir									FLOAT,
	spin_rate_deprecated						FLOAT,
	break_angle_deprecated						FLOAT,
	break_length_deprecated						FLOAT,
	zone_										INT,
	des_										NVARCHAR(500),
	game_type									NVARCHAR(50),
	stand										NVARCHAR(50),
	p_throws									NVARCHAR(50),
	home_team									NVARCHAR(50),
	away_team									NVARCHAR(50),
	type_										NVARCHAR(50),
	hit_location								INT,
	bb_type										NVARCHAR(50),
	balls										INT,
	strikes										INT,
	game_year									INT,
	pfx_x										FLOAT,
	pfx_z										FLOAT,
	plate_x										FLOAT,
	plate_z										FLOAT,
	on_3b										INT,
	on_2b										INT,
	on_1b										INT,
	outs_when_up								INT,
	inning										INT,
	inning_topbot								NVARCHAR(50),
	hc_x										FLOAT,
	hc_y										FLOAT,
	tfs_deprecated								FLOAT,
	tfs_zulu_deprecated							FLOAT,
	umpire										NVARCHAR(50),
	sv_id										NVARCHAR(50),
	vx0											FLOAT,
	vy0											FLOAT,
	vz0											FLOAT,
	ax											FLOAT,
	ay											FLOAT,
	az											FLOAT,
	sz_top										FLOAT,
	sz_bot										FLOAT,
	hit_distance_sc								INT,
	launch_speed								FLOAT,
	launch_angle								INT,
	effective_speed								FLOAT,
	release_spin_rate							INT,
	release_extension							FLOAT,
	game_pk										INT,
	fielder_2									INT,
	fielder_3									INT,
	fielder_4									INT,
	fielder_5									INT,
	fielder_6									INT,
	fielder_7									INT,
	fielder_8									INT,
	fielder_9									INT,
	release_pos_y								FLOAT,
	estimated_ba_using_speedangle				FLOAT,
	estimated_woba_using_speedangle				FLOAT,
	woba_value									FLOAT,
	woba_denom									FLOAT,
	babip_value									FLOAT,
	iso_value									FLOAT,
	launch_speed_angle							INT,
	at_bat_number								INT,
	pitch_number								INT,
	pitch_name									NVARCHAR(50),
	home_score									INT,
	away_score									INT,
	bat_score									INT,
	fld_score									INT,
	post_away_score								INT,
	post_home_score								INT,
	post_bat_score								INT,
	post_fld_score								INT,
	if_fielding_alignment						NVARCHAR(50),
	of_fielding_alignment						NVARCHAR(50),
	spin_axis									INT,
	delta_home_win_exp							FLOAT,
	delta_run_exp								FLOAT,
	bat_speed									FLOAT,
	swing_length								FLOAT,
	estimated_slg_using_speedangle				FLOAT,
	delta_pitcher_run_exp						FLOAT,
	hyper_speed									FLOAT,
	home_score_diff								INT,
	bat_score_diff								INT,
	home_win_exp								FLOAT,
	bat_win_exp									FLOAT,
	age_pit_legacy								INT,
	age_bat_legacy								INT,
	age_pit										INT,
	age_bat										INT,
	n_thruorder_pitcher							INT,
	n_priorpa_thisgame_player_at_bat			INT,
	pitcher_days_since_prev_game				INT,
	batter_days_since_prev_game					INT,
	pitcher_days_until_next_game				INT,
	batter_days_until_next_game					INT,
	api_break_z_with_gravity					FLOAT,
	api_break_x_arm								FLOAT,
	api_break_x_batter_in						FLOAT,
	arm_angle									FLOAT,
	attack_angle								FLOAT,
	attack_direction							FLOAT,
	swing_path_tilt								FLOAT,
	intercept_ball_minus_batter_pos_x_inches	FLOAT,
	intercept_ball_minus_batter_pos_y_inches	FLOAT
)

IF OBJECT_ID('bronze.pitch_data_filtered_pitchers', 'U') IS NOT NULL
	DROP TABLE bronze.pitch_data_filtered_pitchers;

CREATE TABLE bronze.pitch_data_filtered_pitchers (
	pitch_type									NVARCHAR(50),
	game_date									DATE,
	release_speed								FLOAT,
	release_pos_x								FLOAT,
	release_pos_z								FLOAT,
	player_name									NVARCHAR(50),
	batter										INT,
	pitcher										INT,
	events_										NVARCHAR(250),
	description_								NVARCHAR(250),
	spin_dir									FLOAT,
	spin_rate_deprecated						FLOAT,
	break_angle_deprecated						FLOAT,
	break_length_deprecated						FLOAT,
	zone_										INT,
	des_										NVARCHAR(500),
	game_type									NVARCHAR(50),
	stand										NVARCHAR(50),
	p_throws									NVARCHAR(50),
	home_team									NVARCHAR(50),
	away_team									NVARCHAR(50),
	type_										NVARCHAR(50),
	hit_location								INT,
	bb_type										NVARCHAR(50),
	balls										INT,
	strikes										INT,
	game_year									INT,
	pfx_x										FLOAT,
	pfx_z										FLOAT,
	plate_x										FLOAT,
	plate_z										FLOAT,
	on_3b										INT,
	on_2b										INT,
	on_1b										INT,
	outs_when_up								INT,
	inning										INT,
	inning_topbot								NVARCHAR(50),
	hc_x										FLOAT,
	hc_y										FLOAT,
	tfs_deprecated								FLOAT,
	tfs_zulu_deprecated							FLOAT,
	umpire										NVARCHAR(50),
	sv_id										NVARCHAR(50),
	vx0											FLOAT,
	vy0											FLOAT,
	vz0											FLOAT,
	ax											FLOAT,
	ay											FLOAT,
	az											FLOAT,
	sz_top										FLOAT,
	sz_bot										FLOAT,
	hit_distance_sc								INT,
	launch_speed								FLOAT,
	launch_angle								INT,
	effective_speed								FLOAT,
	release_spin_rate							INT,
	release_extension							FLOAT,
	game_pk										INT,
	fielder_2									INT,
	fielder_3									INT,
	fielder_4									INT,
	fielder_5									INT,
	fielder_6									INT,
	fielder_7									INT,
	fielder_8									INT,
	fielder_9									INT,
	release_pos_y								FLOAT,
	estimated_ba_using_speedangle				FLOAT,
	estimated_woba_using_speedangle				FLOAT,
	woba_value									FLOAT,
	woba_denom									FLOAT,
	babip_value									FLOAT,
	iso_value									FLOAT,
	launch_speed_angle							INT,
	at_bat_number								INT,
	pitch_number								INT,
	pitch_name									NVARCHAR(50),
	home_score									INT,
	away_score									INT,
	bat_score									INT,
	fld_score									INT,
	post_away_score								INT,
	post_home_score								INT,
	post_bat_score								INT,
	post_fld_score								INT,
	if_fielding_alignment						NVARCHAR(50),
	of_fielding_alignment						NVARCHAR(50),
	spin_axis									INT,
	delta_home_win_exp							FLOAT,
	delta_run_exp								FLOAT,
	bat_speed									FLOAT,
	swing_length								FLOAT,
	estimated_slg_using_speedangle				FLOAT,
	delta_pitcher_run_exp						FLOAT,
	hyper_speed									FLOAT,
	home_score_diff								INT,
	bat_score_diff								INT,
	home_win_exp								FLOAT,
	bat_win_exp									FLOAT,
	age_pit_legacy								INT,
	age_bat_legacy								INT,
	age_pit										INT,
	age_bat										INT,
	n_thruorder_pitcher							INT,
	n_priorpa_thisgame_player_at_bat			INT,
	pitcher_days_since_prev_game				INT,
	batter_days_since_prev_game					INT,
	pitcher_days_until_next_game				INT,
	batter_days_until_next_game					INT,
	api_break_z_with_gravity					FLOAT,
	api_break_x_arm								FLOAT,
	api_break_x_batter_in						FLOAT,
	arm_angle									FLOAT,
	attack_angle								FLOAT,
	attack_direction							FLOAT,
	swing_path_tilt								FLOAT,
	intercept_ball_minus_batter_pos_x_inches	FLOAT,
	intercept_ball_minus_batter_pos_y_inches	FLOAT
)

IF OBJECT_ID('bronze.games_2015_2025_all_filtered', 'U') IS NOT NULL
	DROP TABLE bronze.games_2015_2025_all_filtered;

CREATE TABLE bronze.games_2015_2025_all_filtered (
	game_id					INT,
	game_datetime			NVARCHAR(50),
	game_date				DATE,
	game_type				NVARCHAR(50),
	game_status				NVARCHAR(50),
	away_name				NVARCHAR(50),
	home_name				NVARCHAR(50),
	away_id					INT,
	home_id					INT,
	doubleheader			NVARCHAR(50),
	game_num				INT,
	home_probable_pitcher	NVARCHAR(50),
	away_probable_pitcher	NVARCHAR(50),
	away_score				NVARCHAR(50),
	home_score				INT,
	current_inning			INT,
	inning_state			NVARCHAR(50),
	venue_id				INT,
	venue_name				NVARCHAR(50),
	series_status			NVARCHAR(50),
	winning_team			NVARCHAR(50),
	losing_team				NVARCHAR(50),
	winning_pitcher			NVARCHAR(50),
	losing_pitcher			NVARCHAR(50),
	save_pitcher			NVARCHAR(50)
);

IF OBJECT_ID('bronze.batters', 'U') IS NOT NULL
	DROP TABLE bronze.batters;

CREATE TABLE bronze.batters (
	name_last			NVARCHAR(50),
	name_first			NVARCHAR(50),
	key_mlbam				INT,
	key_retro			NVARCHAR(50),
	key_bbref			NVARCHAR(50),
	key_fangraphs		INT,
	mlb_played_first	INT,
	mlb_played_last		INT
);

IF OBJECT_ID('bronze.pitchers', 'U') IS NOT NULL
	DROP TABLE bronze.pitchers;

CREATE TABLE bronze.pitchers (
	name_last			NVARCHAR(50),
	name_first			NVARCHAR(50),
	key_mlbam				INT,
	key_retro			NVARCHAR(50),
	key_bbref			NVARCHAR(50),
	key_fangraphs		INT,
	mlb_played_first	INT,
	mlb_played_last		INT
);

IF OBJECT_ID('bronze.opp_batters', 'U') IS NOT NULL
	DROP TABLE bronze.opp_batters;

CREATE TABLE bronze.opp_batters (
	name_last			NVARCHAR(50),
	name_first			NVARCHAR(50),
	key_mlbam				INT,
	key_retro			NVARCHAR(50),
	key_bbref			NVARCHAR(50),
	key_fangraphs		INT,
	mlb_played_first	INT,
	mlb_played_last		INT
);

IF OBJECT_ID('bronze.opp_pitchers', 'U') IS NOT NULL
	DROP TABLE bronze.opp_pitchers;

CREATE TABLE bronze.opp_pitchers (
	name_last			NVARCHAR(50),
	name_first			NVARCHAR(50),
	key_mlbam				INT,
	key_retro			NVARCHAR(50),
	key_bbref			NVARCHAR(50),
	key_fangraphs		INT,
	mlb_played_first	INT,
	mlb_played_last		INT
);

IF OBJECT_ID('bronze.team_info', 'U') IS NOT NULL
	DROP TABLE bronze.team_info;

CREATE TABLE bronze.team_info (
	id				INT,
	name			NVARCHAR(50),
	teamCode		NVARCHAR(50),
	fileCode		NVARCHAR(50),
	teamName		NVARCHAR(50),
	locationName	NVARCHAR(50),
	shortName		NVARCHAR(50)
);
